Update config.yaml

diff --git a/circleci/config.yaml b/circleci/config.yaml
--- a/circleci/config.yaml
+++ b/circleci/config.yaml
@@ -1,40 +1,44 @@
 
 version: 2.1
-jobs:
-  build:
-    docker:
-      - image: cimg/base:2022.09
-    steps:
-      - checkout
-#      - run:
-#          name: Build Application
-  test:
-    docker:
-      - image: cimg/base:2022.09
-    steps:
-      - checkout
-#      - run:
-#          name: Build Application
-  deploy:
-    docker:
-      - image: cimg/base:2022.09
-    steps:
-      - checkout
-#      - run:
-#          name: Build Application
-workflows:
-  springapp:
-    jobs:
-      - build
-      - test:
-          requires:
-            - build
-      - hold:
-          type: approval
-          requires:
-            - build
-            - test
-      - deploy:
-          requires:
-            - hold
 
+jobs:
+  build_and_deploy:
+    docker:
+      - image: cimg/base:2022.09
+    steps:
+      - checkout
+      - cloudrun/init
+      - cloudrun/build:
+          tag: gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}
+      - cloudrun/deploy:
+          image: gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}
+          platform: managed
+          region: us-east1
+          service-name: example-service
+          unauthenticated: true
+      - run:
+          command: >
+            # A simple example of how a deployed managed service could be
+            verified or further tested.
+
+            # This step will send request our "API" and fail if there is
+            unexpected output.
+
+            curl -s "$GCP_DEPLOY_ENDPOINT"
+
+            GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
+
+            if [ "$GCP_API_RESULTS" != "Hello World!" ]; then
+              echo "Result is unexpected"
+              echo 'Result: '
+              curl -s "$GCP_DEPLOY_ENDPOINT"
+              exit 1;
+            fi
+          name: Test managed deployed service.
+orbs:
+  cloudrun: circleci/gcp-cloud-run@1.0.2
+
+workflows:
+  build_and_deploy_to_managed_workflow:
+    jobs:
+      - build_and_deploy
